version: "3.4"

secrets:
  chiakey:
    external: true
  chia_ca.crt:
    external: true
  chia_ca.key:
    external: true
  private_ca.crt:
    external: true
  private_ca.key:
    external: true

services:
  master:
    hostname: chia_master
    image: 192.168.10.40:5050/chia:latest
    volumes:
      - /work/chia/blockchain/db:/root/.chia/mainnet/db
      - /work/chia/blockchain/wallet:/root/.chia/mainnet/wallet
    environment:
      mode: master
      verbose: "true"
      farmer_address: chia_master
    restart: always
    stop_grace_period: 1m
    deploy:
      mode: global
      placement:
        constraints:
        - node.labels.database == true
    ports:
      - "8444:8444"
      - "8447:8447"
    secrets:
    - chiakey
    - chia_ca.crt
    - chia_ca.key
    - private_ca.crt
    - private_ca.key


  harvester:
    image: 192.168.10.40:5050/chia:latest
    volumes:
    - /root/plots:/plots
    environment:
      mode: harvester
      farmer_address: chia_master
      ftp_port: 21
      verbose: "true"
    restart: always
    stop_grace_period: 1m
    deploy:
      mode: global
      placement:
        constraints:
        - node.labels.storage == true
    depends_on:
    - master
    secrets:
    - chiakey
    - chia_ca.crt
    - chia_ca.key
    - private_ca.crt
    - private_ca.key
    
  plotter:
    image: 192.168.10.40:5050/chia:latest
    volumes:
      - /work:/work
      - plots_q:/plots
    environment:
      mode: plotter
      loop: 1
      verbose: "true"
      delay: 0
    restart: "no"
    #stop_grace_period: 7h
    secrets:
    - chiakey
    - chia_ca.crt
    - chia_ca.key
    - private_ca.crt
    - private_ca.key
    deploy:
      mode: replicated
      replicas: 0
      placement:
        constraints:
        - node.labels.compute == true
    #3000s毎に順に起動するなら下記コマンドを実行
    #for I in `seq 1 5`;do docker service scale Chia_plotter=${I};sleep 3000;done 
        
volumes:
  plots_q:
    driver: local
    driver_opts:
      type: cifs
      o: "username=chia,password=xxxxxxxx,rw,vers=3.0"
      device: //192.168.10.100/chia/plots
