apiVersion: v1
kind: ConfigMap
metadata:
  name: chia-config
data:
  pool_list.yaml: |-
    pool:
      pool_list:
      {{- range .Values.poolList }}
        - authentication_public_key: {{ .authenticationPublicKey | quote }}
          launcher_id: {{ .launcherId | quote }}
          owner_public_key: {{ .ownerPublicKey | quote }}
          p2_singleton_puzzle_hash: {{ .p2SingletonPuzzleHash | quote }}
          payout_instructions: {{ .payoutInstructions | quote }}
          pool_url: {{ .poolUrl | quote }}
          target_puzzle_hash: {{ .targetPuzzleHash | quote }}
      {{- end }}

