apiVersion: v1
kind: ConfigMap
metadata:
  name: chia-config
data:
  pool_list.yaml: |-
    pool:
      pool_list:
      {{- range .Values.poolList }}
        - launcher_id: {{ .launcher_id | quote }}
          owner_public_key: {{ .owner_public_key | quote }}
          p2_singleton_puzzle_hash: {{ .p2_singleton_puzzle_hash | quote }}
          payout_instructions: {{ .payout_instructions | quote }}
          pool_url: {{ .pool_url | quote }}
          target_puzzle_hash: {{ .target_puzzle_hash | quote }}
      {{- end }}

