apiVersion: v1
kind: PersistentVolume
metadata:
  name: chia-database
  labels:
    storagetype: database
spec:
  capacity:
    storage: {{ .Values.storage.database.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.database.storageClassName }}
  iscsi:
    targetPortal: {{ .Values.storage.database.iscsi.targetPortal }}
    iqn: {{ .Values.storage.database.iscsi.iqn }}
    lun: {{ .Values.storage.database.iscsi.lun }}
    fsType: {{ .Values.storage.database.iscsi.fsType }}
    readOnly: false
