{{- if not .Values.storage.database.useDynamicProvisioning }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chia-database
  labels:
    storagetype: database
spec:
  capacity:
    storage: {{ .Values.storage.database.fixed.size }}
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: {{ .Values.storage.database.fixed.iscsi.targetPortal }}
    iqn: {{ .Values.storage.database.fixed.iscsi.iqn }}
    lun: {{ .Values.storage.database.fixed.iscsi.lun }}
    fsType: {{ .Values.storage.database.fixed.iscsi.fsType }}
    readOnly: false
---
{{- end }}

