apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.network }}-farmer
spec:
  selector:
    matchLabels:
      app: {{ .Values.network }}-farmer
  template:
    metadata:
      labels:
        app: {{ .Values.network }}-farmer
    spec:
      containers:
      - name: farmer
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: service
          value: 'farmer-only wallet'
        - name: keys
          value: /key/key.txt
        - name: full_node_peer
          value: {{ .Values.network }}-node:{{ .Values.ports.nodePeers }}
        {{ include "chia.commonEnv" . }}
        ports:
        {{ include "chia.ports" . }}
        volumeMounts:
        - mountPath: /chia-ca
          name: secret-ca
        - mountPath: /key
          name: key
        - name: chiaroot
          mountPath: /chia-data
      restartPolicy: Always
      volumes:
      - name: secret-ca
        secret:
          secretName: {{ .Values.network }}-ca
      - name: key
        secret:
          secretName: chiakey
      - name: chiaroot
        emptyDir: {}

