apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.network }}-farmer
spec:
  selector:
    matchLabels:
      app: {{ .Values.network }}-farmer
  template:
    metadata:
      labels:
        app: {{ .Values.network }}-farmer
    spec:
      containers:
      - name: farmer
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: service
          value: 'farmer-only wallet'
        - name: keys
          value: /key/key.txt
        - name: full_node_peer
          value: {{ .Values.network }}-node:{{ .Values.ports.node.peers }}
        {{ include "chia.commonEnv" . | nindent 8 }}
        ports:
        - containerPort: {{ .Values.ports.farmer.peers }}
          name: farmer-peers
          protocol: TCP
        - containerPort: {{ .Values.ports.farmer.rpc }}
          name: farmer-rpc
          protocol: TCP
        - containerPort: {{ .Values.ports.wallet.peers }}
          name: wallet-peers
          protocol: TCP
        - containerPort: {{ .Values.ports.wallet.rpc }}
          name: wallet-rpc
          protocol: TCP
        volumeMounts:
        - mountPath: /chia-ca
          name: secret-ca
        - mountPath: /key
          name: key
<<<<<<< HEAD
        #- name: chiaroot
        #  mountPath: /chia-data
        - name: {{ .Values.network }}-wallet
          mountPath: /chia-data/wallet/db
=======
        - name: chiaroot
          mountPath: /chia-data
>>>>>>> 379f4ad887657ded2771725e4b9a57f03494c6a7
      restartPolicy: Always
      volumes:
      - name: secret-ca
        secret:
          secretName: {{ .Values.network }}-ca
      - name: key
        secret:
          secretName: chiakey
<<<<<<< HEAD
      #- name: chiaroot
      #  emptyDir: {}
=======
      - name: chiaroot
        emptyDir: {}
>>>>>>> 379f4ad887657ded2771725e4b9a57f03494c6a7

