apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainnet-farmer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mainnet-farmer
  template:
    metadata:
      labels:
        app: mainnet-farmer
    spec:
      containers:
        - name: farmer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: service
              value: 'farmer-only'
            - name: CHIA_ROOT
              value: {{ .Values.environment.chiaRoot }}
            - name: ca
              value: {{ .Values.environment.ca }}
            - name: TZ
              value: {{ .Values.environment.TZ }}
            - name: keys
              value: {{ .Values.environment.keys }}
            - name: full_node_peer
              value: {{ .Values.environment.full_node_peer }}
            - name: log_level
              value: {{ .Values.environment.log_level }}
          ports:
            - containerPort: 8447
              name: farmer-peers
              protocol: TCP
            - containerPort: 8559
              name: farmer-rpc
              protocol: TCP
          volumeMounts:
            - mountPath: /chia-ca
              name: secret-ca
            - mountPath: /key
              name: key
            - mountPath: /chia-data
              name: chiaroot
        - name: wallet
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: service
              value: 'wallet'
            - name: CHIA_ROOT
              value: {{ .Values.environment.chiaRoot }}
            - name: ca
              value: {{ .Values.environment.ca }}
            - name: TZ
              value: {{ .Values.environment.TZ }}
            - name: keys
              value: {{ .Values.environment.keys }}
            - name: full_node_peer
              value: {{ .Values.environment.full_node_peer }}
            - name: log_level
              value: {{ .Values.environment.log_level }}
          ports:
            - containerPort: 8449
              name: wallet-peers
              protocol: TCP
            - containerPort: 9256
              name: wallet-rpc
              protocol: TCP
          volumeMounts:
            - mountPath: /chia-ca
              name: secret-ca
            - mountPath: /key
              name: key
            - mountPath: /chia-data
              name: chiaroot
      volumes:
        - name: secret-ca
          secret:
            secretName: mainnet-ca
            defaultMode: 420
        - name: key
          secret:
            secretName: chiakey
            defaultMode: 420
        - name: chiaroot
          emptyDir: {}

