apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.network }}-harvester
spec:
  replicas: {{ len .Values.storage.plots.iscsi }}
  selector:
    matchLabels:
      app: {{ .Values.network }}-harvester
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.network }}-plots
    spec:
      accessModes:
      - ReadOnlyMany
      volumeMode: Filesystem
      storageClassName: {{ .Values.storage.plots.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.storage.plots.size }}
      selector:
        matchLabels:
          storagetype: {{ .Values.storage.plots.storageType }}
  template:
    metadata:
      labels:
        app: {{ .Values.network }}-harvester
    spec:
      volumes:
      - name: secret-ca
        secret:
          secretName: {{ .Values.network }}-ca
          defaultMode: 420
      - name: chiaroot
        emptyDir: {}
      containers:
      - name: exporter
        image: ghcr.io/chia-network/chia-exporter:latest
        ports:
        - name: exporter
          containerPort: {{ .Values.ports.harvester.exporter }}
          protocol: TCP
        env:
        - name: CHIA_EXPORTER_HOSTNAME
          value: localhost
        {{ include "chia.commonEnv" . | nindent 8 }}
        volumeMounts:
        - name: chiaroot
          mountPath: /chia-data
      - name: chia
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - name: daemon
          containerPort: {{ .Values.ports.harvester.daemon }}
          protocol: TCP
        - name: peers
          containerPort: {{ .Values.ports.harvester.peers }}
          protocol: TCP
        - name: rpc
          containerPort: {{ .Values.ports.harvester.rpc }}
          protocol: TCP
        env:
        - name: service
          value: harvester
        - name: recursive_plot_scan
          value: 'true'
        - name: farmer_address
          value: '{{ .Values.network }}-farmer'
        - name: farmer_port
          value: '{{ .Values.ports.farmer.peers }}'
        - name: parallel_decompressor_count
          value: '1'
        - name: decompressor_thread_count
          value: '1'
        {{ include "chia.commonEnv" . | nindent 8 }}
        volumeMounts:
        - name: secret-ca
          mountPath: /chia-ca
        - name: chiaroot
          mountPath: /chia-data
        - name: {{ .Values.network }}-plots
          readOnly: true
          mountPath: /plots
      restartPolicy: Always

