apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mainnet-harvester
  labels:
    app: mainnet-harvester
spec:
  replicas: {{ .Values.replicaCount.harvester }}
  selector:
    matchLabels:
      app: mainnet-harvester
      k8s.chia.net/provenance: ChiaHarvester
  volumeClaimTemplates:
  - metadata:
      name: chia-plots
    spec:
      accessModes: {{ .Values.persistence.plots.accessModes }}
      storageClassName: {{ .Values.persistence.plots.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.persistence.plots.size }}
      selector:
        matchLabels:
          storagetype: plots
  template:
    metadata:
      labels:
        app: mainnet-harvester
        k8s.chia.net.provenance: ChiaHarvester
    spec:
      containers:
      - name: chia
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: service
          value: 'harvester'
        - name: CHIA_ROOT
          value: "{{ .Values.env.chia_root }}"
        - name: ca
          value: "{{ .Values.env.ca }}"
        - name: TZ
          value: "{{ .Values.env.TZ }}"
        - name: recursive_plot_scan
          value: 'true'
        - name: farmer_address
          value: "{{ .Values.env.farmer_address }}"
        - name: farmer_port
          value: "{{ .Values.env.farmer_port }}"
        - name: parallel_decompressor_count
          value: '1'
        - name: decompressor_thread_count
          value: '1'
        - name: log_level
          value: "{{ .Values.env.log_level }}"
        ports:
        {{- range .Values.services.harvester.ports }}
        - containerPort: {{ .port }}
          name: {{ .name }}
          protocol: TCP
        {{- end }}
        volumeMounts:
        - mountPath: /chia-ca
          name: secret-ca
        - mountPath: /chia-data
          name: chiaroot
        - mountPath: /plots
          name: chia-plots
          readOnly: true
      volumes:
      - name: secret-ca
        secret:
          secretName: {{ .Values.secrets.ca }}
      - name: chiaroot
        emptyDir: {}

