apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.network }}-init
spec:
  template:
    metadata:
      name: {{ .Values.network }}-init
      labels:
        app: chia
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      initContainers:
      - name: chia-init-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command:
          - /bin/sh
          - -c
          - |
            chia init && chmod -R a+r /mnt/chia
        env:
        - name: CHIA_ROOT
          value: /mnt/chia
        volumeMounts:
        - name: chia-ssl
          mountPath: /mnt/chia
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          if kubectl get secret {{ .Values.network }}-ca; then
            echo "Secret already exists. Skipping creation."
          else
            kubectl create secret generic {{ .Values.network }}-ca \
              --from-file=/mnt/chia/config/ssl/ca/chia_ca.crt \
              --from-file=/mnt/chia/config/ssl/ca/chia_ca.key \
              --from-file=/mnt/chia/config/ssl/ca/private_ca.crt \
              --from-file=/mnt/chia/config/ssl/ca/private_ca.key
          fi
        volumeMounts:
        - name: chia-ssl
          mountPath: /mnt/chia
      volumes:
      - name: chia-ssl
        emptyDir: {}
      restartPolicy: OnFailure

