---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'node'
      static_configs:
      - targets: 
        - "{{ .Values.network }}-node:9914"
        - "{{ .Values.network }}-farmer:9914"
        - "{{ .Values.network }}-wallet:9914"
        - "{{ .Values.network }}-harvester:9914"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://localhost:9090",
                "version": 1
            }
        ]
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      initContainers:
      - name: init-chown-data
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          mkdir -p /data/grafana /data/prometheus
          chown -R 472:472 /data/grafana
          chown -R 65534:65534 /data/prometheus
        volumeMounts:
        - name: monitor-storage
          mountPath: /data
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - name: grafana
          containerPort: 3000
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: false
        - name: monitor-storage
          mountPath: /var/lib/grafana
          subPath: grafana
      - name: prometheus
        image: prom/prometheus:latest
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.enable-lifecycle'
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: monitor-storage
          mountPath: /prometheus
          subPath: prometheus
      volumes:
      - name: grafana-datasources
        configMap:
          defaultMode: 420
          name: grafana-datasources
      - name: prometheus-config
        configMap:
          name: prometheus-config
  volumeClaimTemplates:
  - metadata:
      name: monitor-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.metrics.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.storage.metrics.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: monitor
spec:
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
  - name: prometheus
    protocol: TCP
    port: 9090
  selector:
    app: monitor
