apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.network }}-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.network }}-node
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.network }}-database
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.storage.database.dynamic.size }}
      {{- if .Values.storage.database.useDynamicProvisioning }}
      storageClassName: {{ .Values.storage.database.dynamic.storageClassName }}
      {{- else }}
      storageClassName: {{ .Values.storage.database.fixed.storageClassName }}
      selector:
        matchLabels:
          storagetype: {{ .Values.storage.database.fixed.storageType }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.network }}-node
    spec:
      volumes:
      - name: secret-ca
        secret:
          secretName: {{ .Values.network }}-ca
          defaultMode: 420
      - name: chiaroot
        emptyDir: {}
      containers:
      - name: exporter
        image: ghcr.io/chia-network/chia-exporter:latest
        ports:
        - name: peers
          containerPort: 9914
          protocol: TCP
        env:
        - name: CHIA_EXPORTER_HOSTNAME
          value: chia
        {{ include "chia.commonEnv" . | nindent 8 }}
        volumeMounts:
        - name: chiaroot
          mountPath: /chia-data
      - name: node
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - name: peers
          containerPort: {{ .Values.ports.node.peers }}
          protocol: TCP
        - name: rpc
          containerPort: {{ .Values.ports.node.rpc }}
          protocol: TCP
        env:
        - name: service
          value: node
        - name: keys
          value: none
        {{ include "chia.commonEnv" . | nindent 8 }}
        volumeMounts:
        - name: secret-ca
          mountPath: /chia-ca
        - name: chiaroot
          mountPath: /chia-data
        - name: {{ .Values.network }}-database
          mountPath: /chia-data/db
        imagePullPolicy: Always
      restartPolicy: Always

