apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.network }}-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.network }}-node
  volumeClaimTemplates:
    - metadata:
        name: chia-database
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        storageClassName: {{ .Values.storage.database.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.storage.database.size }}
        selector:
          matchLabels:
            storagetype: database
  template:
    metadata:
      labels:
        app: {{ .Values.network }}-node
    spec:
      volumes:
        - name: secret-ca
          secret:
            secretName: {{ .Values.network }}-ca
            defaultMode: 420
      containers:
        - name: chia
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: peers
              containerPort: {{ .Values.ports.nodePeers }}
              protocol: TCP
            - name: rpc
              containerPort: {{ .Values.ports.nodeRpc }}
              protocol: TCP
          env:
            - name: service
              value: node
            - name: keys
              value: none
            {{ include "chia.commonEnv" . }}
          volumeMounts:
            - name: secret-ca
              mountPath: /chia-ca
            - name: chia-database
              mountPath: /chia-data/db
      restartPolicy: Always

