{{- range $index, $plot := .Values.storage.plots.iscsi }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.network }}-plots-{{ $index }}
  labels:
    storagetype: {{ $.Values.storage.plots.storageType }}
spec:
  capacity:
    storage: {{ $.Values.storage.plots.size }}
  accessModes:
  - ReadOnlyMany
  storageClassName: {{ $.Values.storage.plots.storageClassName }}
  csi:
    driver: iscsi.csi.k8s.io
    volumeHandle: {{ $.Values.network }}-plots-vol-{{ $index }}
    volumeAttributes:
      targetPortal: {{ $plot.targetPortal }}
      iqn: {{ $plot.iqn }}
      lun: "{{ $plot.lun }}"
      fsType: {{ $plot.fsType }}
      readOnly: "true"
---
{{- end }}
