{{- $network := .Values.network -}}

{{- $serviceTypes := list "node" "farmer" "wallet" "harvester" }}
{{- $portTypes := list "peers" "rpc" }}

{{- range $service := $serviceTypes }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.network }}-{{ $service }}
  labels:
    app: {{ $.Values.network }}-{{ $service }}
spec:
  ports:
  {{- range $portType := $portTypes }}
  - name: {{ $portType }}
    protocol: TCP
    port: {{ index $.Values.ports $service $portType }}
  {{- end }}
  selector:
    app: {{ $.Values.network }}-{{ $service }}
---
{{- end }}
