{{- $network := .Values.network -}}

{{- $services := dict 
    "node" (list 
      (dict "name" "peers" "port" .Values.ports.nodePeers) 
      (dict "name" "rpc" "port" .Values.ports.nodeRpc)
    ) 
    "farmer" (list 
      (dict "name" "farmer-peers" "port" .Values.ports.farmerPeers) 
      (dict "name" "farmer-rpc" "port" .Values.ports.farmerRpc) 
      (dict "name" "wallet-peers" "port" .Values.ports.walletPeers) 
      (dict "name" "wallet-rpc" "port" .Values.ports.walletRpc)
    ) 
    "harvester" (list 
      (dict "name" "peers" "port" .Values.ports.harvesterPeers) 
      (dict "name" "rpc" "port" .Values.ports.harvesterRpc)
    )
-}}

{{- range $service, $ports := $services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $network }}-{{ $service }}
  labels:
    app: {{ $network }}-{{ $service }}
spec:
  ports:
  {{- range $port := $ports }}
    - name: {{ $port.name }}
      protocol: TCP
      port: {{ $port.port }}
  {{- end }}
  selector:
    app: {{ $network }}-{{ $service }}
---
{{- end }}

