{{- range $service, $config := .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service }}
  labels:
    app: {{ $service }}
spec:
  type: {{ $.Values.service.type }}
  selector:
    app: {{ $service }}
  ports:
  {{- range $port := $config.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      protocol: {{ $port.protocol | default "TCP" }}
  {{- end }}
---
{{- end }}

