apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.network }}-wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.network }}-wallet
  template:
    metadata:
      labels:
        app: {{ .Values.network }}-wallet
    spec:
      containers:
      - name: wallet
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: service
          value: 'wallet'
        - name: keys
          value: /key/key.txt
        - name: full_node_peer
          value: {{ .Values.network }}-node:{{ .Values.ports.node.peers }}
        {{ include "chia.commonEnv" . | nindent 8 }}
        ports:
        - containerPort: {{ .Values.ports.wallet.peers }}
          name: peers
          protocol: TCP
        - containerPort: {{ .Values.ports.wallet.rpc }}
          name: rpc
          protocol: TCP
        volumeMounts:
        - mountPath: /chia-ca
          name: secret-ca
        - mountPath: /key
          name: key
        - name: chiaroot
          mountPath: /chia-data
      restartPolicy: Always
      volumes:
      - name: secret-ca
        secret:
          secretName: {{ .Values.network }}-ca
      - name: key
        secret:
          secretName: chiakey
      - name: chiaroot
        emptyDir: {}

