apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainnet-farmer
spec:
  selector:
    matchLabels:
      app: mainnet-farmer
      k8s.chia.net/provenance: ChiaFarmer
  template:
    metadata:
      labels:
        app: mainnet-farmer
        k8s.chia.net/provenance: ChiaFarmer
    spec:
      containers:
      - env:
        - name: service
          value: 'wallet farmer-only'
        - name: CHIA_ROOT
          value: /chia-data
        - name: ca
          value: /chia-ca
        - name: TZ
          value: UTC
        - name: keys
          value: /key/key.txt
        - name: full_node_peer
          value: mainnet-node:8444
        - name: farmer_address
          value: mainnet-farmer
        - name: farmer_port
          value: "8447"
        - name: log_level
          value: INFO
        image: ghcr.io/chia-network/chia:latest
        imagePullPolicy: Always
        name: chia
        ports:
        - containerPort: 55400
          name: daemon
          protocol: TCP
        - containerPort: 8447
          name: farmer-peers
          protocol: TCP
        - containerPort: 8559
          name: farmer-rpc
          protocol: TCP
        - containerPort: 8449
          name: wallet-peers
          protocol: TCP
        - containerPort: 9256
          name: wallet-rpc
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /chia-ca
          name: secret-ca
        - mountPath: /key
          name: key
        - mountPath: /chia-data
          name: chiaroot
      restartPolicy: Always
      volumes:
      - name: secret-ca
        secret:
          defaultMode: 420
          secretName: mainnet-ca
      - name: key
        secret:
          defaultMode: 420
          secretName: chiakey
      - emptyDir: {}
        name: chiaroot
