apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mainnet-farmer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainnet-farmer
  volumeClaimTemplates:
  - metadata:
      name: chia-wallet
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
  template:
    metadata:
      labels:
        app: mainnet-farmer
    spec:
      volumes:
      - name: secret-ca
        secret:
          secretName: mainnet-ca
      - name: key
        secret:
          secretName: chiakey
      - emptyDir: {}
        name: chiaroot
      containers:
      - name: farmer
        image: ghcr.io/chia-network/chia:latest
        env:
        - name: service
          value: farmer-only
        - name: CHIA_ROOT
          value: /chia-data
        - name: ca
          value: /chia-ca
        - name: TZ
          value: UTC
        - name: keys
          value: /key/key.txt
        - name: full_node_peer
          value: mainnet-node:8444
        - name: log_level
          value: INFO
        ports:
        - containerPort: 8447
          name: farmer-peers
          protocol: TCP
        - containerPort: 8559
          name: farmer-rpc
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: secret-ca
          mountPath: /chia-ca
        - name: key
          mountPath: /key
        - name: chiaroot
          mountPath: /chia-data
      - name: wallet
        image: ghcr.io/chia-network/chia:latest
        env:
        - name: service
          value: wallet
        - name: CHIA_ROOT
          value: /chia-data
        - name: ca
          value: /chia-ca
        - name: TZ
          value: UTC
        - name: keys
          value: /key/key.txt
        - name: full_node_peer
          value: mainnet-node:8444
        - name: log_level
          value: INFO
        ports:
        - containerPort: 8449
          name: wallet-peers
          protocol: TCP
        - containerPort: 9256
          name: wallet-rpc
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: secret-ca
          mountPath: /chia-ca
        - name: key
          mountPath: /key
        - name: chiaroot
          mountPath: /chia-data
        - name: chia-wallet
          mountPath: /chia-data/wallet
      restartPolicy: Always
