network: mainnet

# Image configuration
image:
  repository: ghcr.io/chia-network/chia
  tag: latest

# Port numbers
ports:
  farmer:
    daemon: 55400
    peers: 8447
    rpc: 8559
    exporter: 9914
  wallet:
    daemon: 55400
    peers: 8449
    rpc: 9256
    exporter: 9914
  harvester:
    daemon: 55400
    peers: 8448
    rpc: 8560
    exporter: 9914
  node:
    daemon: 55400
    peers: 8444
    rpc: 8555
    exporter: 9914

security:
  fsGroup: 2000
  runAsUser: 1000


# Persistent Volume Configurations
storage:
  metrics:
    size: 1Gi
    storageClassName: qnap-sc
  database:
    useDynamicProvisioning: true
    fixed:
      storageType: database
      storageClassName: iscsi-static
      size: 250Gi
      iscsi:
        targetPortal: 192.168.1.112
        iqn: iqn.2004-04.com.qnap:ts-832px:iscsi.database.576194
        lun: 0
        fsType: ext4
    dynamic:
      size: 250Gi
      storageClassName: qnap-sc
  plots:
    size: 1Gi
    storageType: plots
    storageClassName: iscsi-static
    iscsi:
      - targetPortal: 192.168.1.110
        iqn: iqn.2024-10.localdomain.omv1:target3
        lun: 1
        fsType: xfs
      - targetPortal: 192.168.1.110
        iqn: iqn.2024-05.localdomain.omv1:target1
        lun: 1
        fsType: xfs
      - targetPortal: 192.168.1.110
        iqn: iqn.2024-05.localdomain.omv1:target2
        lun: 1
        fsType: xfs
      - targetPortal: 192.168.1.111
        iqn: iqn.2004-04.com.qnap:ts-832x:iscsi.target1.506276
        lun: 1
        fsType: xfs
      - targetPortal: 192.168.1.112
        iqn: iqn.2004-04.com.qnap:ts-832px:iscsi.target.576194
        lun: 1
        fsType: xfs

# Service Account
serviceAccount: chia-service-account

# Common Environment Variables
env:
  chiaRoot: /chia-data
  caPath: /chia-ca
  timezone: UTC
  logLevel: INFO
  upnp: 'false'

poolList:
  - launcherId: '0x1ac89396b6d25abd0dea42709d740814337fb96fe56b23149ca32014a11e1da0'
    ownerPublicKey: '0x962d21272e7a589bff0d0bf77492e03e3e1c89d674ba00306920a891078a869a15a02c3ce29440f89ece768c1eaae22d'
    p2SingletonPuzzleHash: '0x4d379db4ca7a516fa6c73bba3d4c3dcf424bce96ca2b6ede0d5192e5f12655f1'
    payoutInstructions: d857ae8c7178921421e4f71b26514fc0e61c50efdf2e530050dab4651d69edbc
    poolUrl: https://xch.spacefarmers.io
    targetPuzzleHash: '0x61751cc01a73d5e64a07d6e37b451eed9f157f04da53e3c7d06f355928ba2113'


