replicaCount:
  harvester: 5
  node: 1

image:
  repository: ghcr.io/chia-network/chia
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP

persistence:
  database:
    enabled: true
    storageClass: iscsi-static
    accessModes:
      - ReadWriteOnce
    size: 250Gi
  plots:
    enabled: true
    storageClass: iscsi-static
    accessModes:
      - ReadWriteOnce
    size: 1Gi

env:
  TZ: UTC
  log_level: INFO
  farmer_address: mainnet-farmer
  farmer_port: 8447
  full_node_peer: mainnet-node:8444
  keys: /key/key.txt
  chia_root: /chia-data
  ca: /chia-ca

services:
  farmer:
    ports:
      - name: daemon
        port: 55400
      - name: farmer-peers
        port: 8447
      - name: farmer-rpc
        port: 8559
      - name: wallet-peers
        port: 8449
      - name: wallet-rpc
        port: 9256
  harvester:
    ports:
      - name: daemon
        port: 55400
      - name: peers
        port: 8448
      - name: rpc
        port: 8560
  node:
    ports:
      - name: daemon
        port: 55400
      - name: peers
        port: 8444
      - name: rpc
        port: 8555
  wallet:
    ports:
      - name: daemon
        port: 55400
      - name: peers
        port: 8449
      - name: rpc
        port: 9256

secrets:
  ca: mainnet-ca
  key: chiakey

