network: mainnet

# Image configuration
image:
  repository: ghcr.io/chia-network/chia
  tag: latest

# Port numbers
ports:
  farmer:
    peers: 8447
    rpc: 8559
  wallet:
    peers: 8449
    rpc: 9256
  harvester:
    peers: 8448
    rpc: 8560
  node:
    peers: 8444
    rpc: 8555

# Persistent Volume Configurations
storage:
  database:
    useDynamicProvisioning: true
    fixed:
      storageClassName: iscsi-static
      size: 250Gi
      iscsi:
        targetPortal: 192.168.1.112
        iqn: iqn.2004-04.com.qnap:ts-832px:iscsi.database.576194
        lun: 0
        fsType: ext4
    dynamic:
      size: 250Gi
      storageClassName: qnap-sc
  plots:
    size: 1Gi
    storageClassName: iscsi-static
    iscsi:
      - targetPortal: 192.168.1.110
        iqn: iqn.2024-05.localdomain.omv1:target0
        lun: 1
        fsType: xfs
      - targetPortal: 192.168.1.110
        iqn: iqn.2024-05.localdomain.omv1:target1
        lun: 1
        fsType: xfs
      - targetPortal: 192.168.1.110
        iqn: iqn.2024-05.localdomain.omv1:target2
        lun: 1
        fsType: xfs
      - targetPortal: 192.168.1.111
        iqn: iqn.2004-04.com.qnap:ts-832x:iscsi.target1.506276
        lun: 1
        fsType: xfs
      - targetPortal: 192.168.1.112
        iqn: iqn.2004-04.com.qnap:ts-832px:iscsi.target.576194
        lun: 1
        fsType: xfs

# Service Account
serviceAccount: chia-service-account

# Common Environment Variables
env:
  chiaRoot: /chia-data
  caPath: /chia-ca
  timezone: UTC
  logLevel: INFO

