apiVersion: v1
kind: PersistentVolume
metadata:
  name: chia-database
  labels:
    storagetype: database
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-static
  iscsi:
    targetPortal: 192.168.1.56
    iqn: iqn.2004-04.com.qnap:ts-832px:iscsi.database.576194
    lun: 0
    fsType: 'ext4'
    readOnly: false
