apiVersion: v1
kind: PersistentVolume
metadata:
  name: chia-plots-0
  labels:
    storagetype: plots
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-static
  iscsi:
    targetPortal: 192.168.1.110
    iqn: iqn.2024-05.localdomain.omv1:target0
    lun: 1
    fsType: 'xfs'
    readOnly: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chia-plots-1
  labels:
    storagetype: plots
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-static
  iscsi:
    targetPortal: 192.168.1.110
    iqn: iqn.2024-05.localdomain.omv1:target1
    lun: 1
    fsType: 'xfs'
    readOnly: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chia-plots-2
  labels:
    storagetype: plots
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-static
  iscsi:
    targetPortal: 192.168.1.110
    iqn: iqn.2024-05.localdomain.omv1:target2
    lun: 1
    fsType: 'xfs'
    readOnly: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chia-plots-3
  labels:
    storagetype: plots
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-static
  iscsi:
    targetPortal: 192.168.1.111
    iqn: iqn.2004-04.com.qnap:ts-832x:iscsi.target1.506276
    lun: 1
    fsType: 'xfs'
    readOnly: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chia-plots-4
  labels:
    storagetype: plots
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-static
  iscsi:
    targetPortal: 192.168.1.112
    iqn: iqn.2004-04.com.qnap:ts-832px:iscsi.target.576194
    lun: 1
    fsType: 'xfs'
    readOnly: true
